prev_next.settings:
  type: config_object
  mapping:
    batch_size:
      type: integer
      label: 'Batch Size'

prev_next.node_type.*:
  type: config_object
  label: 'Previous Next Content Type settings'
  mapping:
    include:
      type: boolean
      label: 'Include'
    current:
      type: string
      label: 'Current'
    indexing_criteria:
      type: string
      label: 'Indexing Criteria'
    indexing_criteria_current:
      type: string
      label: 'Indexing criteria Current'
    same_type:
      type: boolean
      label: 'Same type'
    same_type_current:
      type: string
      label: 'Same type Current'
